name: Release

on:
  push:
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release
      - name: Package
        run: docker build -t ${GITHUB_REPOSITORY}:$(echo $GITHUB_REF | grep -oE "[^/]+$") .
